import { Document, Types } from "mongoose";

export interface IComment extends Document {
  _id: Types.ObjectId;
  content: string;
  projectId: Types.ObjectId | string; // Reference to the project
  author: {
    userId: Types.ObjectId | string; // Reference to the user
    fullName: string;
    avatar?: string;
  };
  createdAt?: Date;
  updatedAt?: Date;
}

export interface ILike extends Document {
  _id: Types.ObjectId;
  likedBy: {
    userId: Types.ObjectId | string;
    fullName: string;
    avatar?: string;
  }; // The user who liked the project
  projectId: Types.ObjectId | string; // The project that was liked
  createdAt: Date;
}

export interface IBookmark extends Document {
  _id: Types.ObjectId;
  userId: Types.ObjectId | string; // Reference to the User model
  projectId: Types.ObjectId | string; // Reference to the Project model
  createdAt: Date;
}

export interface IMessage extends Document {
  sender: string; // User ID of the sender
  recipient: string; // User ID of the recipient
  text: string; // Message content
  deleted: boolean; // Soft delete flag
  conversationId: string;
  createdAt?: Date; // Auto-generated by default
}

export interface IUserInfo {
  userId: Types.ObjectId | string; // Reference to the User model
  fullName: string;
  avatar?: string; // Optional, in case the user has no avatar
}

export interface IFollow extends Document {
  _id: Types.ObjectId;
  follower: IUserInfo; // The user who is following
  following: IUserInfo; // The user being followed
  followedAt?: Date; // Optional, auto-generated by default
}
